import React from "react";
import { useTranslation } from 'react-i18next';

export default function () {
	const { t } = useTranslation('common')

	return (
		<React.Fragment>
			<h1>{t("terms.conditions.title")}</h1>
			<p>{t("terms.conditions.date")}</p>
			<ol>
				<li>{t("terms.conditions.object")}</li>
			</ol>
			<p>
				{t("terms.conditions.first")}
			</p>
			<ol >
				<li>{t("terms.conditions.ownership")}</li>
			</ol>
			<p>
				{t("terms.conditions.second")}
			</p>
			<p>
				{t("terms.conditions.third")}
			</p>
			<p>&nbsp;</p>
			<ol>
				<li>{t("terms.conditions.application")}</li>
			</ol>
			<p>
				{t("terms.conditions.fourth")}
			</p>
			<ol >
				<li>{t("terms.conditions.fullage")}</li>
			</ol>
			<p>
				{t("terms.conditions.fifth")}
			</p>
			<ul>
				<li>
					{t("terms.conditions.sixth")}
				</li>
				<li>
					{t("terms.conditions.seventh")}
				</li>
				<li>
					{t("terms.conditions.eighth")}
				</li>
			</ul>
			<p>&nbsp;</p>
			<p>
				{t("terms.conditions.nineth")}
			</p>
			<p>
				{t("terms.conditions.tenth")}
			</p>
			<p>
				{t("terms.conditions.eleventh")}
			</p>
			<p>
				{t("terms.conditions.twelveth")}
			</p>
			<ol >
				<li>{t("terms.conditions.use")}</li>
			</ol>
			<p>
				{t("terms.conditions.thirteenth")}
			</p>
			<p>
				{t("terms.conditions.fourteenth")}
			</p>
			<p>
				{t("terms.conditions.fifteenth")}
			</p>
			<p>
				{t("terms.conditions.sixteenth")}
			</p>
			<p>
				{t("terms.conditions.seventeenth")}
			</p>
			<ol>
				<li>{t("terms.conditions.responsibility")}</li>
			</ol>
			<p>
				{t("terms.conditions.eighteenth")}
			</p>
			<p>
				{t("terms.conditions.nineteenth")}
			</p>
			<ul>
				<li>
					{t("terms.conditions.twentieth")}
				</li>
				<li>{t("terms.conditions.twentyfirst")}</li>
				<li>
					{t("terms.conditions.twentysecond")}
				</li>
				<li>{t("terms.conditions.twentythird")}</li>
				<li>
					{t("terms.conditions.twentyfourth")}
				</li>
				<li>
					{t("terms.conditions.twentyfifth")}
				</li>
				<li>
					{t("terms.conditions.twentysixth")}
				</li>
				<li>
					{t("terms.conditions.twentyseventh")}
				</li>
				<li>
					{t("terms.conditions.twentyeighth")}
				</li>
				<li>{t("terms.conditions.twentynineth")}</li>
				<li>
					{t("terms.conditions.thirtieth")}
				</li>
			</ul>
			<p>
				{t("terms.conditions.thirtyfirst")}
			</p>
			<p>
				{t("terms.conditions.thirtysecond")}
			</p>
			<p>
				{t("terms.conditions.thirtythird")}
			</p>
			<p>
				{t("terms.conditions.thirtyfourth")}
			</p>
			<p>
				{t("terms.conditions.thirtyfifth")}
			</p>
			<ol >
				<li>{t("terms.conditions.thirtysixth")}</li>
			</ol>
			<p>
				{t("terms.conditions.thirtyseventh")}
			</p>
			<p>
				{t("terms.conditions.thirtyeight")}
			</p>
			<p>
				{t("terms.conditions.thirtynineth")}
			</p>
			<ol >
				<li>{t("terms.conditions.fourty")}</li>
			</ol>
			<p>
				{t("terms.conditions.fourtyfirst")}
			</p>
			<p>
				{t("terms.conditions.fourtysecond")}
			</p>
			<p>
				{t("terms.conditions.fourtythird")}
			</p>
			<p>&nbsp;</p>
			<ol >
				<li>
					{t("terms.conditions.fourtyfourth")}
				</li>
			</ol>
			<p>
				{t("terms.conditions.fourtyfifth")}
			</p>
			<p>&nbsp;</p>
			<ol >
				<li>{t("terms.conditions.compensation")}</li>
			</ol>
			<p>
				{t("terms.conditions.fourtysixth")}
			</p>
			<ol >
				<li>{t("terms.conditions.others")}</li>
			</ol>
			<p>
				{t("terms.conditions.fourtyseventh")}
			</p>
			<p>
				{t("terms.conditions.fourtyeight")}
			</p>
			<p>
				{t("terms.conditions.fourtynineth")}
			</p>
			<p>
				{t("terms.conditions.fifty")}
			</p>
			<p>{t("terms.conditions.support")}</p>
		</React.Fragment>
	);
}
