export interface Claims {
    id?: any
    username?: string
}

export enum Districts {
    BRENA = "Breña",
    LAVICTORIA = "La Victoria",
    LIMA = "Centro de Lima",
    LINCE = "Lince",
    RIMAC = "Rímac",
    BARRANCO = "Barranco",
    JESUSMARIA = "Jesús María",
    LAMOLINA = "La Molina",
    MAGDALENA = "Magdalena",
    MIRAFLORES = "Miraflores",
    PUEBLOLIBRE = "Pueblo Libre",
    SANBORJA = "San Borja",
    SANISIDRO = "San Isidro",
    SANLUIS = "San Luis",
    SANMIGUEL = "San Miguel",
    SANTIAGODESURCO = "Santiago de Surco",
    SURQUILLO = "Surquillo",
    ATE = "Ate",
    CIENEGUILLA = "Cieneguilla",
    CHACLACAYO = "Chaclacayo",
    SANJUANDELURIGANCHO = "San Juan de Lurigancho",
    ELAGUSTINO = "El Agustino",
    CHOSICA = "Chosica",
    SANTAANITA = "Santa Anita",
    ANCON = "Ancón",
    CARABAYLLO = "Carabayllo",
    COMAS = "Comas",
    INDEPENDENCIA = "Independencia",
    LOSOLIVOS = "Los Olivos",
    PUENTEPIEDRA = "Puente Piedra",
    SANMARTINDEPORRES = "San Martín de Porres",
    SANTAROSA = "Santa Rosa",
    CHORRILLOS = "Chorrillos",
    LURIN = "Lurín",
    PACHACAMAC = "Pachacamac",
    PUCUSANA = "Pucusana",
    PUNTAHERMOSA = "Punta Hermosa",
    PUNTANEGRA = "Punta Negra",
    SANBARTOLO = "San Bartolo",
    SANJUANDEMIRAFLORES = "San Juan de Miraflores",
    SANTAMARIADELMAR = "Santa María del Mar",
    VILLAELSALVADOR = "Villa el Salvador",
    VILLAMARIADELTRIUNFO = "Villa María del Triunfo",
}

export const PROTECTED_FIELDS = "-password -refresh_token"
