PUT http://localhost:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlZGE3MGFmOWM3MTZhNDU2NDBlN2FkNCIsInVzZXJuYW1lIjoiSm9zZTAxMDIiLCJpYXQiOjE1OTE1Nzk1NDcsImV4cCI6MTU5MTU4MzE0N30.430yNHbmyZpe7os9UnPWIuKgse1eZqdGPZZ61jZTlPM
Content-Type: application/json

{
    "price":"12.45",
    "eyes":"blue"
}