export const DISTRICTS = [
    "",
    "Breña",
    "La Victoria",
    "Centro de Lima",
    "Lince",
    "Rímac",
    "Barranco",
    "Jesús María",
    "La Molina",
    "Magdalena",
    "Miraflores",
    "Pueblo Libre",
    "San Borja",
    "San Isidro",
    "San Luis",
    "San Miguel",
    "Santiago de Surco",
    "Surquillo",
    "Ate",
    "Cieneguilla",
    "Chaclacayo",
    "San Juan de Lurigancho",
    "El Agustino",
    "Chosica",
    "Santa Anita",
    "Ancón",
    "Carabayllo",
    "Comas",
    "Independencia",
    "Los Olivos",
    "Puente Piedra",
    "San Martín de Porres",
    "Santa Rosa",
    "Chorrillos",
    "Lurín",
    "Pachacamac",
    "Pucusana",
    "Punta Hermosa",
    "Punta Negra",
    "San Bartolo",
    "San Juan de Miraflores",
    "Santa María del Mar",
    "Villa el Salvador",
    "Villa María del Triunfo",
]
export const SERVICES = [
    "",
    "Trato de pareja",
    "Sexo oral",
    "Sexo anal",
    "Oral con condón",
    "Oral natural",
    "Eyaculación facial",
    "Masajes",
    "Fantasías",
    "Trío",
    "Beso Negro",
    "Fetichismo",
    "Sado duro",
    "Sado suave",
]

export const Zodiac = [
    "",
    "Aries",
    "Tauro",
    "Géminis",
    "Cáncer",
    "Leo",
    "Virgo",
    "Libra",
    "Escorpio",
    "Sagitario",
    "Capricornio",
    "Acuario",
    "Piscis",
]

export const Ethnicities = ["", "Andinas", "Morenas", "Piel Blanca", "Trigueña"]

export const Orientations = ["", "Heterosexual", "Homosexual", "Bisexual", "Trans"]

export const MIN_AGE = 18
export const MAX_AGE = 99
export const MIN_PRICE = 0.0
