name: Kinesya

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.4.2
    - run: npm install
    - run: npm test
    - run: npm run dev
    env:
       JWT_KEY : jwt
       R_JWT_KEY: refresh
